### ISSUE TITLE
File descriptor in the “Read Write Camera Registers” page

### ISSUE THREAD

**Issue by raymonlo-git** [HULKs/NaoV6#2]
Hi @rkost, in the code you share in your “Read Write Camera Registers” page, would you mind also sharing the code for opening the file descriptor? I don’t know how to open the file descriptor for accessing the cameras on NAO. It would be great if you can share the missing piece.

**Comment by rkost** [comment]
If you only need the code for opening the fd this is it:

```
  device = (camera_ == Camera::TOP) ? "/dev/video-top" : "/dev/video-bottom";
  fd_ = open(device.c_str(), O_RDWR | O_NONBLOCK);
  if (fd_ < 0)
  {
    // bad state
  }
```
